package com.example.bkeattacker;

/**
 * Consumer helper class: blocking retrieval of GATT event data from the Go layer
 * <p>
 * Methods in this class will block the current thread until new data arrives from the Go layer.
 * It is recommended to call these methods in a background thread to avoid blocking the main thread (e.g., Android UI thread).
 */
public class Consumer {

    /**
     * Blocks and waits for a GATT RPC request JSON string, then returns it.
     * <p>
     * This method will block until a new GATT RPC event is available from the Go layer.
     *
     * @return The JSON string of the GATT RPC (e.g., {"method":"read","service":"..."})
     * @throws UnsatisfiedLinkError If the native library is not correctly loaded
     */
    public static native String PopGattRpc();

    /**
     * Blocks and waits for a string representation of Service Data, then returns it.
     * <p>
     * Typically used to receive broadcast data (e.g., service data in BLE advertisements).
     *
     * @return The Service Data string (content determined by the Go layer, could be hex, base64, or raw string)
     * @throws UnsatisfiedLinkError If the native library is not correctly loaded
     */
    public static native String PopServiceData();

    // Static initialization block: loads the native library generated by Go
    static {
        // The library name must match 'xxx' in 'go build -o libxxx.so'
        // For example: go build -buildmode=c-shared -o libgo_kcp_client.so ...
        System.loadLibrary("go_kcp_client");
    }
}
